// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rhuModBot;

#nullable disable

namespace rhuModBot.Migrations
{
    [DbContext(typeof(PostContext))]
    [Migration("20220130052152_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("rhuModBot.DbPost", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("articleTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("domainIsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isReported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("linkedArticle")
                        .HasColumnType("TEXT");

                    b.Property<string>("postTitle")
                        .HasColumnType("TEXT");

                    b.Property<double>("similarity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("userIsIgnored")
                        .HasColumnType("INTEGER");

                    b.HasKey("key");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
